version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  user-service:
    image: moonshot-user-service
    deploy:
      replicas: 2
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db
    command: sh -c "until nc -z db 5432; do echo waiting for db; sleep 1; done; npm run start"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "4000:80"  # Expose NGINX on host port 4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    external: true
